server:
  port: 8081

spring:
  application:
    name: video-auth
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
        namespace: video-platform
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 307655
  data:
    redis:
      host: localhost
      port: 6379

# JWT配置
jwt:
  secret: video-platform-secret-key-2024-very-long-secret-abcdewdfdsfsdffgsd
  access-token-expiration: 7200
  refresh-token-expiration: 604800
